Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: lab-04-key

Resources:
  LabInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LabInstanceRole
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ec2.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - cloudformation:*
                  - apigateway:*
                  - execute-api:*
                  - lambda:*
                  - s3:*
                  - iam:*
                  - ec2:*

  LabInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref LabInstanceRole

  LabInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow inbound SSH connections
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  LabInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref LabInstanceSecurityGroup
      InstanceType: t2.nano
      AvailabilityZone: eu-west-1a
      ImageId: ami-70edb016
      IamInstanceProfile: !Ref LabInstanceProfile
      Tags:
        -
          Key: Name
          Value: Lab04