AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: API Gateway Endpoint configured using Swagger specified inline and backed by a Lambda functions

Parameters:
  ServiceName:
    Description: Name of the exported endpoint
    Type: String
    Default: lab-04-service

Resources:
  MoodApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              /sad:
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SadLambdaFunction.Arn}/invocations
                  responses: {}
              /happy:
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HappyLambdaFunction.Arn}/invocations
                  responses: {}
            swagger: '2.0'

  SadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./sad/
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: ./sad
            Method: GET
            RestApiId: 
                Ref: MoodApi

  HappyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./happy/
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /happy
            Method: GET
            RestApiId:
                Ref: MoodApi

Outputs:
  ApiUrl:
    Description: URL of the API endpoint
    Value: !Sub https://${MoodApi}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
        Name: !Ref ServiceName